[lint.flake8-type-checking]
# Add quotes around type annotations, if doing so would allow
# an import to be moved into a type-checking block.
quote-annotations = true

[lint.per-file-ignores]
"alembic/env.py" = ["F401"]

[lint]
extend-select = ["I"]