"""initial_revision

Revision ID: eb0f5867387d
Revises:
Create Date: 2024-06-26 13:19:06.409715

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb0f5867387d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "headers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["template_id"], ["templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_headers_template_id"), "headers", ["template_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["user_roles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_users_role_id"), "users", ["role_id"], unique=False)
    op.create_table(
        "access_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_access_tokens_user_id"), "access_tokens", ["user_id"], unique=True
    )
    op.create_table(
        "filled_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["creator_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["template_id"], ["templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_filled_templates_creator_id"),
        "filled_templates",
        ["creator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_filled_templates_template_id"),
        "filled_templates",
        ["template_id"],
        unique=False,
    )
    op.create_table(
        "filledtemplates__users",
        sa.Column("filled_template_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["filled_template_id"], ["filled_templates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index(
        op.f("ix_filledtemplates__users_filled_template_id"),
        "filledtemplates__users",
        ["filled_template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_filledtemplates__users_user_id"),
        "filledtemplates__users",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "result_for_headers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("filled_template_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["filled_template_id"], ["filled_templates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["player_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_result_for_headers_filled_template_id"),
        "result_for_headers",
        ["filled_template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_result_for_headers_player_id"),
        "result_for_headers",
        ["player_id"],
        unique=False,
    )
    op.create_table(
        "result_for_headers__headers",
        sa.Column("result_for_header", sa.Integer(), nullable=True),
        sa.Column("header", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["header"], ["headers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["result_for_header"], ["result_for_headers.id"], ondelete="CASCADE"
        ),
    )
    op.create_index(
        op.f("ix_result_for_headers__headers_header"),
        "result_for_headers__headers",
        ["header"],
        unique=False,
    )
    op.create_index(
        op.f("ix_result_for_headers__headers_result_for_header"),
        "result_for_headers__headers",
        ["result_for_header"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_result_for_headers__headers_result_for_header"),
        table_name="result_for_headers__headers",
    )
    op.drop_index(
        op.f("ix_result_for_headers__headers_header"),
        table_name="result_for_headers__headers",
    )
    op.drop_table("result_for_headers__headers")
    op.drop_index(
        op.f("ix_result_for_headers_player_id"), table_name="result_for_headers"
    )
    op.drop_index(
        op.f("ix_result_for_headers_filled_template_id"),
        table_name="result_for_headers",
    )
    op.drop_table("result_for_headers")
    op.drop_index(
        op.f("ix_filledtemplates__users_user_id"), table_name="filledtemplates__users"
    )
    op.drop_index(
        op.f("ix_filledtemplates__users_filled_template_id"),
        table_name="filledtemplates__users",
    )
    op.drop_table("filledtemplates__users")
    op.drop_index(
        op.f("ix_filled_templates_template_id"), table_name="filled_templates"
    )
    op.drop_index(op.f("ix_filled_templates_creator_id"), table_name="filled_templates")
    op.drop_table("filled_templates")
    op.drop_index(op.f("ix_access_tokens_user_id"), table_name="access_tokens")
    op.drop_table("access_tokens")
    op.drop_index(op.f("ix_users_role_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_headers_template_id"), table_name="headers")
    op.drop_table("headers")
    op.drop_table("user_roles")
    op.drop_table("templates")
    # ### end Alembic commands ###
